//Rutas de los jugadores
###
GET http://localhost:3000/players/ HTTP/1.1

###
POST http://localhost:3000/players/add HTTP/1.1
Content-Type: application/json

{
    "nombre":"Jal117",
    "password":"123456"
}

###
PUT http://localhost:3000/players/actualizarPuntuacion HTTP/1.1
Content-Type: application/json

{
    "id_usuario":1,
    "totalVictorias":1
}

###
GET http://localhost:3000/players/buscarUsuario HTTP/1.1
Content-Type: application/json

{
    "nombre":"Jal117",
    "password":"123456"
}


//Rutas de la partida
###
GET http://localhost:3000/match/ HTTP/1.1

###
POST http://localhost:3000/match/add HTTP/1.1
Content-Type: application/json

{
    "id_partida": 3,
    "palabra": "pala",
    "estado": "perdida",
    "id_participante1": 1,
    "id_participante2": 2,
    "id_participante3": 3
}